# Generated by Django 3.2.18 on 2023-04-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_draw', '0003_auto_20230408_0107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('raffle', 'ip_address'), ('raffle', 'verification_code')},
        ),
    ]
