# Generated by Django 3.2.18 on 2023-04-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_draw', '0004_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='raffle_draw.raffle'),
        ),
    ]
