# Generated by Django 3.2.18 on 2023-04-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle_draw', '0005_auto_20230408_2225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('raffle', 'verification_code'), ('raffle', 'ticket_number'), ('raffle', 'ip_address')},
        ),
    ]
